apiVersion: apps/v1
kind: Deployment
metadata:
  name: boat-app-apm
  namespace: dev
  labels:
    app: boat-app-apm
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: boat-app-apm
    tags.datadoghq.com/version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boat-app-apm
  template:
    metadata:
      labels:
        admission.datadoghq.com/enabled: 'true'
        app: boat-app-apm
        tags.datadoghq.com/env: dev
        tags.datadoghq.com/service: boat-app-apm
        tags.datadoghq.com/version: 1.0.0
      annotations:
        admission.datadoghq.com/js-lib.version: latest
    spec:
      containers:
        - name: boat-app-apm
          image: swr.ap-southeast-2.myhuaweicloud.com/princhealth/boat-app-apm:latest
          env:
            - name: ECHO_MSG
              valueFrom:
                secretKeyRef:
                  name: boat-app-apm
                  key: ECHO_MSG
      imagePullSecrets:
        - name: default-secret
